export var headshots = {
  // hdc
  reyan           : "/assets/img/headshots/hdc/Reyan.jpg",
  cscullyallison  : "/assets/img/headshots/hdc/cscullyallison.png",
  jixianli        : "/assets/img/headshots/hdc/jixianli.jpg",
  jiangkairong    : "/assets/img/headshots/hdc/jiangkairong.jpg",
  kawilliams      : "/assets/img/headshots/hdc/kawilliams.jpg",
  dilshadurrahman : "/assets/img/headshots/hdc/dilshadurrahman.png",
  mingwei         : "/assets/img/headshots/hdc/mingwei.jpg",
  rfaust          : "/assets/img/headshots/hdc/rfaust.jpg",
  sabin           : "/assets/img/headshots/hdc/sabin.jpg",
  simon           : "/assets/img/headshots/hdc/simon.jpg",
  zhenge          : "/assets/img/headshots/hdc/zhenge.jpg",
  bigelow         : "/assets/img/headshots/hdc/bigelow.png",
  iqbal           : "/assets/img/headshots/hdc/iqbal.png",
  cscheid         : "/assets/img/headshots/hdc/cscheid.png",
  josh            : "/assets/img/headshots/hdc/josh.jpg",
  kisaacs         : "/assets/img/headshots/hdc/kisaacs.jpg",
  skobourov       : "/assets/img/headshots/hdc/skobourov.jpg",

  // friends (+hdc alumni)
  glickenstein    : "/assets/img/headshots/friends/glickenstein.jpg",
  remco           : "/assets/img/headshots/friends/remco.jpg",
  kindlmann       : "/assets/img/headshots/friends/kindlmann.jpg",
  sorelle         : "/assets/img/headshots/friends/sorelle.jpg",
  suresh          : "/assets/img/headshots/friends/suresh.jpg",
  dylan           : "/assets/img/headshots/friends/dylan-cashman.jpg",
  yongwang        : "/assets/img/headshots/friends/yongwang.jpg",
  huaminqu        : "/assets/img/headshots/friends/huaminqu.jpg",
  archambault     : "/assets/img/headshots/friends/archambault.jpg",
  sabrinanusrat   : "/assets/img/headshots/friends/sabrinanusrat.jpg",
  bahadorsaket    : "/assets/img/headshots/friends/bahadorsaket.jpg",
  rosen           : "/assets/img/headshots/friends/rosen.jpg",
  beiwang         : "/assets/img/headshots/friends/beiwang.jpg",
  nivan           : "/assets/img/headshots/friends/nivan.jpg",
  berger          : "/assets/img/headshots/friends/berger.jpg",
  correll         : "/assets/img/headshots/friends/correll.jpg",
  comba           : "/assets/img/headshots/friends/comba.jpg"
};
  
