name: Carlos Scheidegger
markdown: kramdown
url: http://cscheid.net
highlighter: pygments
exclude: ['scripts', 'Makefile']
plugins:
  - jekyll-last-modified-at
asset_bundler:
  compress:
    js: false
    css: false
  base_path: /bundles/
  server_url:
  remove_bundled: false
  dev: false
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"
